
(()=>{'use strict';
const D=window.MASTER_DATA||[], S=window.ATLAS_SYSTEMS||[];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const accent={respiratorio:'#38bdf8',circulatorio:'#f472b6',linfatico:'#34d399'};
const escape=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function progressFor(id,count){try{if(id==='respiratorio'){const p=JSON.parse(localStorage.getItem('atlasResp.progress.v2')||'{}');return Object.values(p).filter(Boolean).length}if(id==='linfatico'){const p=JSON.parse(localStorage.getItem('atlasLinf.progress.v1')||'{}');return Object.values(p).filter(Boolean).length}if(id==='circulatorio'){const p=JSON.parse(localStorage.getItem('atlasState')||'{}');return Object.values(p.studied||{}).filter(Boolean).length}}catch{}return 0}
function renderSystems(){const host=$('#systemGrid');host.innerHTML=S.map(s=>{const done=progressFor(s.id,s.count),pct=Math.round(done/s.count*100);return `<article class="system-card" style="--accent:${accent[s.id]}"><div class="system-icon">${s.icon}</div><h3>${escape(s.label)}</h3><p>${escape(s.desc)}</p><div class="system-meta"><span>${s.count} alvos</span><span>${escape(s.range)}</span></div><div class="progress-label"><span>Progresso neste dispositivo</span><b>${done}/${s.count}</b></div><div class="progress-track"><div class="progress-fill" style="width:${pct}%"></div></div><a class="open-system" href="${s.href}"><span>Abrir atlas</span><span>→</span></a></article>`}).join('');const totalDone=S.reduce((n,s)=>n+progressFor(s.id,s.count),0);$('#globalDone').textContent=Math.round(totalDone/D.length*100)+'%';$('#totalTargets').textContent=D.length}
let filter='all';
function linkFor(x){return `sistemas/${x.system}/index.html?q=${encodeURIComponent(x.name)}`}
function renderSearch(){const q=norm($('#globalSearch').value.trim());let arr=D.filter(x=>(filter==='all'||x.system===filter)&&(!q||norm(`${x.code} ${x.name} ${x.group} ${x.block}`).includes(q)));if(!q) arr=[];$('#searchMeta').textContent=q?`${arr.length} resultado${arr.length===1?'':'s'} em ${filter==='all'?'todos os sistemas':S.find(s=>s.id===filter)?.label||filter}.`:`Digite para pesquisar em ${D.length} alvos.`;$('#searchResults').innerHTML=arr.slice(0,80).map(x=>`<a class="result" href="${linkFor(x)}"><span class="result-code">${escape(x.code)}</span><span><strong>${escape(x.name)}</strong><small>${escape(x.group)}${x.block&&x.block!==x.group?' • '+escape(x.block):''}</small></span><span class="result-system">${escape(x.systemLabel)} →</span></a>`).join('')}
function renderMaster(){const host=$('#masterLists');host.innerHTML=S.map((s,si)=>{const items=D.filter(x=>x.system===s.id);const groups=[...new Set(items.map(x=>x.group||'Geral'))];return `<details class="master-system" ${si===0?'open':''}><summary>${escape(s.label)} <span>${items.length} alvos</span></summary><div class="master-groups">${groups.map(g=>`<section class="master-group"><h4>${escape(g)}</h4>${items.filter(x=>(x.group||'Geral')===g).map(x=>`<a class="master-item" href="${linkFor(x)}"><code>${escape(x.code)}</code><span>${escape(x.name)}</span><small>abrir →</small></a>`).join('')}</section>`).join('')}</div></details>`}).join('')}
$('#globalSearch').addEventListener('input',renderSearch);$('#clearSearch').onclick=()=>{$('#globalSearch').value='';renderSearch();$('#globalSearch').focus()};$('#systemFilters').addEventListener('click',e=>{const b=e.target.closest('[data-system]');if(!b)return;filter=b.dataset.system;$$('#systemFilters .chip').forEach(x=>x.classList.toggle('active',x===b));renderSearch()});
$('#printMaster').onclick=()=>{document.querySelectorAll('.master-system').forEach(d=>d.open=true);setTimeout(()=>window.print(),60)};
$('#contrastBtn').onclick=()=>{document.body.classList.toggle('high-contrast');localStorage.setItem('atlasIntegrado.contrast',document.body.classList.contains('high-contrast')?'1':'0')};if(localStorage.getItem('atlasIntegrado.contrast')==='1')document.body.classList.add('high-contrast');
let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(!deferred)return;deferred.prompt();await deferred.userChoice;deferred=null;$('#installBtn').classList.add('hidden')};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.warn);
renderSystems();renderMaster();renderSearch();
})();
